name: Release Pipeline

on:
  workflow_dispatch:
jobs:
  deploy_local:
    runs-on: hpzbookg9

    steps:
    - name: Stop Website
      run: Stop-IISSite -Name "API Service" -Confirm:$false

    - name: Prepare local folders
      run: |       
        Remove-Item 'c:\pub\hbapi_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\hbapi_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\hbapi hbapi_bak
        md c:\pub\hbapi
        
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: BuildPipeline.yml
        name: artifacts
        path: c:\pub\hbapi

    - name: Start Website
      run: Start-IISSite -Name "API Service"


  deploy_remote:
    needs: deploy_local
    runs-on: win2019dc03
    environment:
      name: IIS_Environment.Prod

    steps:
    - name: Stop Website
      run: Stop-IISSite -Name "API Service" -Confirm:$false

    - name: Prepare local folders
      run: |       
        Remove-Item 'c:\pub\hbapi_bak1' -Recurse -ErrorAction Ignore
        Remove-Item 'c:\pub\hbapi_bak' -Recurse -ErrorAction Ignore
        ren c:\pub\hbapi hbapi_bak
        md c:\pub\hbapi
        
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: BuildPipeline.yml
        name: artifacts
        path: c:\pub\hbapi

    - name: Start Website
      run: Start-IISSite -Name "API Service"

